#############################################################################
# Makefile for building: datajockey
# Generated by qmake (2.01a) (Qt 4.7.2) on: Sun Feb 19 15:14:38 2012
# Project:  datajockey.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile datajockey.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I. -Iinclude/audio -Iinclude/controller -Iinclude/view -I/usr/include/rubberband -I/usr/include/rasqal -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lsndfile -lvorbisfile -lmad -ljack -ljackcpp -lrubberband -lslv2 -lQtDBus -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/audio/audiobuffer.cpp \
		src/audio/audioio.cpp \
		src/audio/beatbuffer.cpp \
		src/audio/command.cpp \
		src/audio/doublelinkedlist.cpp \
		src/audio/master.cpp \
		src/audio/player.cpp \
		src/audio/schedulenode.cpp \
		src/audio/scheduler.cpp \
		src/audio/soundfile.cpp \
		src/audio/stretcher.cpp \
		src/audio/stretcher_rate.cpp \
		src/audio/timepoint.cpp \
		src/audio/transport.cpp \
		src/controller/audiobufferreference.cpp \
		src/controller/audiocontroller.cpp \
		src/controller/audioloaderthread.cpp \
		src/view/main.cpp \
		src/view/waveformitem.cpp moc/moc_audiocontroller.cpp \
		moc/moc_audioloaderthread.cpp
OBJECTS       = obj/audiobuffer.o \
		obj/audioio.o \
		obj/beatbuffer.o \
		obj/command.o \
		obj/doublelinkedlist.o \
		obj/master.o \
		obj/player.o \
		obj/schedulenode.o \
		obj/scheduler.o \
		obj/soundfile.o \
		obj/stretcher.o \
		obj/stretcher_rate.o \
		obj/timepoint.o \
		obj/transport.o \
		obj/audiobufferreference.o \
		obj/audiocontroller.o \
		obj/audioloaderthread.o \
		obj/main.o \
		obj/waveformitem.o \
		obj/moc_audiocontroller.o \
		obj/moc_audioloaderthread.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		datajockey.pro
QMAKE_TARGET  = datajockey
DESTDIR       = 
TARGET        = datajockey

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: datajockey.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile datajockey.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile datajockey.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/datajockey1.0.0 || $(MKDIR) obj/datajockey1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/datajockey1.0.0/ && $(COPY_FILE) --parents include/audio/audiobuffer.hpp include/audio/audioio.hpp include/audio/beatbuffer.hpp include/audio/command.hpp include/audio/doublelinkedlist.hpp include/audio/master.hpp include/audio/player.hpp include/audio/scheduledataparser.hpp include/audio/schedulenode.hpp include/audio/scheduler.hpp include/audio/soundfile.hpp include/audio/stretcher.hpp include/audio/stretcher_rate.hpp include/audio/timepoint.hpp include/audio/transport.hpp include/audio/types.hpp include/controller/audiobufferreference.hpp include/controller/audiocontroller.hpp include/controller/audioloaderthread.hpp include/view/waveformitem.hpp obj/datajockey1.0.0/ && $(COPY_FILE) --parents src/audio/audiobuffer.cpp src/audio/audioio.cpp src/audio/beatbuffer.cpp src/audio/command.cpp src/audio/doublelinkedlist.cpp src/audio/master.cpp src/audio/player.cpp src/audio/schedulenode.cpp src/audio/scheduler.cpp src/audio/soundfile.cpp src/audio/stretcher.cpp src/audio/stretcher_rate.cpp src/audio/timepoint.cpp src/audio/transport.cpp src/controller/audiobufferreference.cpp src/controller/audiocontroller.cpp src/controller/audioloaderthread.cpp src/view/main.cpp src/view/waveformitem.cpp obj/datajockey1.0.0/ && (cd `dirname obj/datajockey1.0.0` && $(TAR) datajockey1.0.0.tar datajockey1.0.0 && $(COMPRESS) datajockey1.0.0.tar) && $(MOVE) `dirname obj/datajockey1.0.0`/datajockey1.0.0.tar.gz . && $(DEL_FILE) -r obj/datajockey1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_audiocontroller.cpp moc/moc_audioloaderthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_audiocontroller.cpp moc/moc_audioloaderthread.cpp
moc/moc_audiocontroller.cpp: include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp \
		include/audio/audioio.hpp \
		include/controller/audiocontroller.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/controller/audiocontroller.hpp -o moc/moc_audiocontroller.cpp

moc/moc_audioloaderthread.cpp: include/controller/audiocontroller.hpp \
		include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp \
		include/audio/audioio.hpp \
		include/controller/audioloaderthread.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/controller/audioloaderthread.hpp -o moc/moc_audioloaderthread.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/audiobuffer.o: src/audio/audiobuffer.cpp include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/audiobuffer.o src/audio/audiobuffer.cpp

obj/audioio.o: src/audio/audioio.cpp include/audio/audioio.hpp \
		include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/audioio.o src/audio/audioio.cpp

obj/beatbuffer.o: src/audio/beatbuffer.cpp include/audio/beatbuffer.hpp \
		include/audio/timepoint.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/beatbuffer.o src/audio/beatbuffer.cpp

obj/command.o: src/audio/command.cpp include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/command.o src/audio/command.cpp

obj/doublelinkedlist.o: src/audio/doublelinkedlist.cpp include/audio/doublelinkedlist.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/doublelinkedlist.o src/audio/doublelinkedlist.cpp

obj/master.o: src/audio/master.cpp include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/master.o src/audio/master.cpp

obj/player.o: src/audio/player.cpp include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/master.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp \
		include/audio/stretcher_rate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/player.o src/audio/player.cpp

obj/schedulenode.o: src/audio/schedulenode.cpp include/audio/schedulenode.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/schedulenode.o src/audio/schedulenode.cpp

obj/scheduler.o: src/audio/scheduler.cpp include/audio/scheduler.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/schedulenode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/scheduler.o src/audio/scheduler.cpp

obj/soundfile.o: src/audio/soundfile.cpp include/audio/soundfile.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/soundfile.o src/audio/soundfile.cpp

obj/stretcher.o: src/audio/stretcher.cpp include/audio/stretcher.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/stretcher.o src/audio/stretcher.cpp

obj/stretcher_rate.o: src/audio/stretcher_rate.cpp include/audio/stretcher_rate.hpp \
		include/audio/stretcher.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/stretcher_rate.o src/audio/stretcher_rate.cpp

obj/timepoint.o: src/audio/timepoint.cpp include/audio/timepoint.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/timepoint.o src/audio/timepoint.cpp

obj/transport.o: src/audio/transport.cpp include/audio/transport.hpp \
		include/audio/timepoint.hpp \
		include/audio/command.hpp \
		include/audio/types.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/transport.o src/audio/transport.cpp

obj/audiobufferreference.o: src/controller/audiobufferreference.cpp include/controller/audiobufferreference.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/controller/audiocontroller.hpp \
		include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp \
		include/audio/audioio.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/audiobufferreference.o src/controller/audiobufferreference.cpp

obj/audiocontroller.o: src/controller/audiocontroller.cpp include/controller/audiocontroller.hpp \
		include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp \
		include/audio/audioio.hpp \
		include/controller/audioloaderthread.hpp \
		include/controller/audiobufferreference.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/audiocontroller.o src/controller/audiocontroller.cpp

obj/audioloaderthread.o: src/controller/audioloaderthread.cpp include/controller/audioloaderthread.hpp \
		include/controller/audiocontroller.hpp \
		include/audio/master.hpp \
		include/audio/player.hpp \
		include/audio/command.hpp \
		include/audio/timepoint.hpp \
		include/audio/types.hpp \
		include/audio/transport.hpp \
		include/audio/audiobuffer.hpp \
		include/audio/soundfile.hpp \
		include/audio/beatbuffer.hpp \
		include/audio/stretcher.hpp \
		include/audio/scheduler.hpp \
		include/audio/schedulenode.hpp \
		include/audio/audioio.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/audioloaderthread.o src/controller/audioloaderthread.cpp

obj/main.o: src/view/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/view/main.cpp

obj/waveformitem.o: src/view/waveformitem.cpp include/view/waveformitem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/waveformitem.o src/view/waveformitem.cpp

obj/moc_audiocontroller.o: moc/moc_audiocontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_audiocontroller.o moc/moc_audiocontroller.cpp

obj/moc_audioloaderthread.o: moc/moc_audioloaderthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_audioloaderthread.o moc/moc_audioloaderthread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

